name: docker

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Authorize at Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build & Push
      uses: docker/build-push-action@v6.16.0
      with:
        tags: |
          wilddev/weather:${{ github.ref_name }}
          wilddev/weather:latest
        push: true
